apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - minio-init-job.yaml
  - agent-migrate-job.yaml
  - erpx-mock.yaml
  - agent-service.yaml
  - agent-workers.yaml
  - agent-scheduler.yaml
  - ui.yaml
  - ingress.yaml

