apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounting-agent-staging

resources:
  - namespace.yaml
  - default-serviceaccount.yaml
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: replicas-patch.yaml
  - path: nodeselector-patch.yaml
  - path: agent-service-llm-envfrom-patch.yaml
  - path: resources-patch.yaml
  - path: services-nodeport-patch.yaml

images:
  - name: accounting-agent-layer/agent-service
    newName: ghcr.io/mapleleaflatte03/accounting-agent-layer/agent-service
    newTag: staging-latest
  - name: accounting-agent-layer/agent-worker
    newName: ghcr.io/mapleleaflatte03/accounting-agent-layer/agent-worker
    newTag: staging-latest
  - name: accounting-agent-layer/agent-scheduler
    newName: ghcr.io/mapleleaflatte03/accounting-agent-layer/agent-scheduler
    newTag: staging-latest
  - name: accounting-agent-layer/erpx-mock-api
    newName: ghcr.io/mapleleaflatte03/accounting-agent-layer/erpx-mock-api
    newTag: staging-latest
  - name: accounting-agent-layer/ui
    newName: ghcr.io/mapleleaflatte03/accounting-agent-layer/ui
    newTag: staging-latest
